//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.19 at 01:26:29 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(
		xmlns = { 
				@XmlNs(prefix = "tipos", namespaceURI = "http://issdigital.campinas.sp.gov.br/WsNFe2/tp")
				}, 
				namespace = "http://localhost:8080/WsNFe2/lote",
				location = "http://localhost:8080/WsNFe2/lote http://issdigital.campinas.sp.gov.br/WsNFe2/xsd/RetornoConsultaLote.xsd"
		)
package br.com.dsfnet.nfse.wsnfe2.lote.retornoConsultaLote;
import javax.xml.bind.annotation.XmlNs;
