//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.09 at 07:39:25 PM BRST 
//


package br.com.dsfnet.nfse.wsnfe2.lote.consultaSeqRPS;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cabecalho">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CodCid" type="{http://localhost:8080/WsNFe2/tp}tpCodCidade"/>
 *                   &lt;element name="IMPrestador" type="{http://localhost:8080/WsNFe2/tp}tpInscricaoMunicipal"/>
 *                   &lt;element name="CPFCNPJRemetente" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJ"/>
 *                   &lt;element name="SeriePrestacao" type="{http://localhost:8080/WsNFe2/tp}tpSeriePrestacao" minOccurs="0"/>
 *                   &lt;element name="Versao" type="{http://localhost:8080/WsNFe2/tp}tpVersao"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cabecalho"
})
@XmlRootElement(name = "ConsultaSeqRps", namespace = "http://localhost:8080/WsNFe2/lote")
public class ConsultaSeqRps {

    @XmlElement(name = "Cabecalho", required = true)
    protected ConsultaSeqRps.Cabecalho cabecalho;

    /**
     * Gets the value of the cabecalho property.
     * 
     * @return
     *     possible object is
     *     {@link ConsultaSeqRps.Cabecalho }
     *     
     */
    public ConsultaSeqRps.Cabecalho getCabecalho() {
        return cabecalho;
    }

    /**
     * Sets the value of the cabecalho property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsultaSeqRps.Cabecalho }
     *     
     */
    public void setCabecalho(ConsultaSeqRps.Cabecalho value) {
        this.cabecalho = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CodCid" type="{http://localhost:8080/WsNFe2/tp}tpCodCidade"/>
     *         &lt;element name="IMPrestador" type="{http://localhost:8080/WsNFe2/tp}tpInscricaoMunicipal"/>
     *         &lt;element name="CPFCNPJRemetente" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJ"/>
     *         &lt;element name="SeriePrestacao" type="{http://localhost:8080/WsNFe2/tp}tpSeriePrestacao" minOccurs="0"/>
     *         &lt;element name="Versao" type="{http://localhost:8080/WsNFe2/tp}tpVersao"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codCid",
        "imPrestador",
        "cpfcnpjRemetente",
        "seriePrestacao",
        "versao"
    })
    public static class Cabecalho {

        @XmlElement(name = "CodCid")
        protected long codCid;
        @XmlElement(name = "IMPrestador")
        protected long imPrestador;
        @XmlElement(name = "CPFCNPJRemetente", required = true)
        protected String cpfcnpjRemetente;
        @XmlElement(name = "SeriePrestacao")
        protected Byte seriePrestacao;
        @XmlElement(name = "Versao")
        protected long versao;

        /**
         * Gets the value of the codCid property.
         * 
         */
        public long getCodCid() {
            return codCid;
        }

        /**
         * Sets the value of the codCid property.
         * 
         */
        public void setCodCid(long value) {
            this.codCid = value;
        }

        /**
         * Gets the value of the imPrestador property.
         * 
         */
        public long getIMPrestador() {
            return imPrestador;
        }

        /**
         * Sets the value of the imPrestador property.
         * 
         */
        public void setIMPrestador(long value) {
            this.imPrestador = value;
        }

        /**
         * Gets the value of the cpfcnpjRemetente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCPFCNPJRemetente() {
            return cpfcnpjRemetente;
        }

        /**
         * Sets the value of the cpfcnpjRemetente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCPFCNPJRemetente(String value) {
            this.cpfcnpjRemetente = value;
        }

        /**
         * Gets the value of the seriePrestacao property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSeriePrestacao() {
            return seriePrestacao;
        }

        /**
         * Sets the value of the seriePrestacao property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSeriePrestacao(Byte value) {
            this.seriePrestacao = value;
        }

        /**
         * Gets the value of the versao property.
         * 
         */
        public long getVersao() {
            return versao;
        }

        /**
         * Sets the value of the versao property.
         * 
         */
        public void setVersao(long value) {
            this.versao = value;
        }

    }

}
