//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.19 at 01:26:29 PM BRT 
//

package br.com.dsfnet.nfse.wsnfe2.lote;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.dsfnet.nfse.util.XMLGregorianCalendarAdapter;
import br.com.dsfnet.nfse.wsnfe2.tp.TpLote;
import br.com.dsfnet.nfse.wsnfe2.tp.TpMetodoEnvio;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cabecalho">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CodCidade" type="{http://localhost:8080/WsNFe2/tp}tpCodCidade"/>
 *                   &lt;element name="CPFCNPJRemetente" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJ"/>
 *                   &lt;element name="RazaoSocialRemetente" type="{http://localhost:8080/WsNFe2/tp}tpRazaoSocial"/>
 *                   &lt;element name="transacao" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="dtInicio" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="dtFim" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="QtdRPS" type="{http://localhost:8080/WsNFe2/tp}tpQtdRpsLote"/>
 *                   &lt;element name="ValorTotalServicos" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
 *                   &lt;element name="ValorTotalDeducoes" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
 *                   &lt;element name="Versao" type="{http://localhost:8080/WsNFe2/tp}tpVersao"/>
 *                   &lt;element name="MetodoEnvio" type="{http://localhost:8080/WsNFe2/tp}tpMetodoEnvio"/>
 *                   &lt;element name="VersaoComponente" type="{http://localhost:8080/WsNFe2/tp}tpVersaoComponente" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Lote" type="{http://localhost:8080/WsNFe2/tp}tpLote"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "cabecalho", "lote" })
@XmlRootElement(name = "ReqEnvioLoteRPS", namespace = "http://localhost:8080/WsNFe2/lote")
public class ReqEnvioLoteRPS {

	@XmlElement(name = "Cabecalho", required = true)
	protected ReqEnvioLoteRPS.Cabecalho cabecalho;

	@XmlElement(name = "Lote", required = true)
	protected TpLote lote;

	/**
	 * Gets the value of the cabecalho property.
	 * 
	 * @return possible object is {@link ReqEnvioLoteRPS.Cabecalho }
	 * 
	 */
	public ReqEnvioLoteRPS.Cabecalho getCabecalho() {
		return cabecalho;
	}

	/**
	 * Sets the value of the cabecalho property.
	 * 
	 * @param value
	 *            allowed object is {@link ReqEnvioLoteRPS.Cabecalho }
	 * 
	 */
	public void setCabecalho(ReqEnvioLoteRPS.Cabecalho value) {
		this.cabecalho = value;
	}

	/**
	 * Gets the value of the lote property.
	 * 
	 * @return possible object is {@link TpLote }
	 * 
	 */
	public TpLote getLote() {
		return lote;
	}

	/**
	 * Sets the value of the lote property.
	 * 
	 * @param value
	 *            allowed object is {@link TpLote }
	 * 
	 */
	public void setLote(TpLote value) {
		this.lote = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="CodCidade" type="{http://localhost:8080/WsNFe2/tp}tpCodCidade"/>
	 *         &lt;element name="CPFCNPJRemetente" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJ"/>
	 *         &lt;element name="RazaoSocialRemetente" type="{http://localhost:8080/WsNFe2/tp}tpRazaoSocial"/>
	 *         &lt;element name="transacao" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
	 *         &lt;element name="dtInicio" type="{http://www.w3.org/2001/XMLSchema}date"/>
	 *         &lt;element name="dtFim" type="{http://www.w3.org/2001/XMLSchema}date"/>
	 *         &lt;element name="QtdRPS" type="{http://localhost:8080/WsNFe2/tp}tpQtdRpsLote"/>
	 *         &lt;element name="ValorTotalServicos" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
	 *         &lt;element name="ValorTotalDeducoes" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
	 *         &lt;element name="Versao" type="{http://localhost:8080/WsNFe2/tp}tpVersao"/>
	 *         &lt;element name="MetodoEnvio" type="{http://localhost:8080/WsNFe2/tp}tpMetodoEnvio"/>
	 *         &lt;element name="VersaoComponente" type="{http://localhost:8080/WsNFe2/tp}tpVersaoComponente" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "codCidade", "cpfcnpjRemetente", "razaoSocialRemetente", "transacao", "dtInicio", "dtFim", "qtdRPS",
			"valorTotalServicos", "valorTotalDeducoes", "versao", "metodoEnvio", "versaoComponente" })
	public static class Cabecalho {

		@XmlElement(name = "CodCidade")
		protected long codCidade;
		@XmlElement(name = "CPFCNPJRemetente", required = true)
		protected String cpfcnpjRemetente;
		@XmlElement(name = "RazaoSocialRemetente", required = true)
		protected String razaoSocialRemetente;
		@XmlElement(defaultValue = "true")
		protected boolean transacao;
		
		@XmlElement(required = true)
		@XmlSchemaType(name = "date")
		@XmlJavaTypeAdapter(XMLGregorianCalendarAdapter.class)
		protected XMLGregorianCalendar dtInicio;
		@XmlElement(required = true)
		@XmlSchemaType(name = "date")
		@XmlJavaTypeAdapter(XMLGregorianCalendarAdapter.class)
		protected XMLGregorianCalendar dtFim;
		
		@XmlElement(name = "QtdRPS")
		protected int qtdRPS;
		@XmlElement(name = "ValorTotalServicos", required = true)
		protected BigDecimal valorTotalServicos;
		@XmlElement(name = "ValorTotalDeducoes", required = true)
		protected BigDecimal valorTotalDeducoes;
		@XmlElement(name = "Versao")
		protected long versao;
		@XmlElement(name = "MetodoEnvio", required = true)
		protected TpMetodoEnvio metodoEnvio;
		@XmlElement(name = "VersaoComponente")
		protected String versaoComponente;

		/**
		 * Gets the value of the codCidade property.
		 * 
		 */
		public long getCodCidade() {
			return codCidade;
		}

		/**
		 * Sets the value of the codCidade property.
		 * 
		 */
		public void setCodCidade(long value) {
			this.codCidade = value;
		}

		/**
		 * Gets the value of the cpfcnpjRemetente property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCPFCNPJRemetente() {
			return cpfcnpjRemetente;
		}

		/**
		 * Sets the value of the cpfcnpjRemetente property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCPFCNPJRemetente(String value) {
			this.cpfcnpjRemetente = value;
		}

		/**
		 * Gets the value of the razaoSocialRemetente property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRazaoSocialRemetente() {
			return razaoSocialRemetente;
		}

		/**
		 * Sets the value of the razaoSocialRemetente property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRazaoSocialRemetente(String value) {
			this.razaoSocialRemetente = value;
		}

		/**
		 * Gets the value of the transacao property.
		 * 
		 */
		public boolean isTransacao() {
			return transacao;
		}

		/**
		 * Sets the value of the transacao property.
		 * 
		 */
		public void setTransacao(boolean value) {
			this.transacao = value;
		}

		/**
		 * Gets the value of the dtInicio property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getDtInicio() {
			return dtInicio;
		}

		/**
		 * Sets the value of the dtInicio property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setDtInicio(XMLGregorianCalendar value) {
			this.dtInicio = value;
		}

		/**
		 * Gets the value of the dtFim property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getDtFim() {
			return dtFim;
		}

		/**
		 * Sets the value of the dtFim property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setDtFim(XMLGregorianCalendar value) {
			this.dtFim = value;
		}

		/**
		 * Gets the value of the qtdRPS property.
		 * 
		 */
		public int getQtdRPS() {
			return qtdRPS;
		}

		/**
		 * Sets the value of the qtdRPS property.
		 * 
		 */
		public void setQtdRPS(int value) {
			this.qtdRPS = value;
		}

		/**
		 * Gets the value of the valorTotalServicos property.
		 * 
		 * @return possible object is {@link BigDecimal }
		 * 
		 */
		public BigDecimal getValorTotalServicos() {
			return valorTotalServicos;
		}

		/**
		 * Sets the value of the valorTotalServicos property.
		 * 
		 * @param value
		 *            allowed object is {@link BigDecimal }
		 * 
		 */
		public void setValorTotalServicos(BigDecimal value) {
			this.valorTotalServicos = value;
		}

		/**
		 * Gets the value of the valorTotalDeducoes property.
		 * 
		 * @return possible object is {@link BigDecimal }
		 * 
		 */
		public BigDecimal getValorTotalDeducoes() {
			return valorTotalDeducoes;
		}

		/**
		 * Sets the value of the valorTotalDeducoes property.
		 * 
		 * @param value
		 *            allowed object is {@link BigDecimal }
		 * 
		 */
		public void setValorTotalDeducoes(BigDecimal value) {
			this.valorTotalDeducoes = value;
		}

		/**
		 * Gets the value of the versao property.
		 * 
		 */
		public long getVersao() {
			return versao;
		}

		/**
		 * Sets the value of the versao property.
		 * 
		 */
		public void setVersao(long value) {
			this.versao = value;
		}

		/**
		 * Gets the value of the metodoEnvio property.
		 * 
		 * @return possible object is {@link TpMetodoEnvio }
		 * 
		 */
		public TpMetodoEnvio getMetodoEnvio() {
			return metodoEnvio;
		}

		/**
		 * Sets the value of the metodoEnvio property.
		 * 
		 * @param value
		 *            allowed object is {@link TpMetodoEnvio }
		 * 
		 */
		public void setMetodoEnvio(TpMetodoEnvio value) {
			this.metodoEnvio = value;
		}

		/**
		 * Gets the value of the versaoComponente property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getVersaoComponente() {
			return versaoComponente;
		}

		/**
		 * Sets the value of the versaoComponente property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setVersaoComponente(String value) {
			this.versaoComponente = value;
		}

	}

}
