//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.09 at 07:32:35 PM BRST 
//


package br.com.dsfnet.nfse.wsnfe2.lote.consultaLote;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cabecalho">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CodCidade" type="{http://localhost:8080/WsNFe2/tp}tpCodCidade"/>
 *                   &lt;element name="CPFCNPJRemetente" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJ"/>
 *                   &lt;element name="Versao" type="{http://localhost:8080/WsNFe2/tp}tpVersao"/>
 *                   &lt;element name="NumeroLote" type="{http://localhost:8080/WsNFe2/tp}tpNumero"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cabecalho"
})
@XmlRootElement(name = "ReqConsultaLote", namespace = "http://localhost:8080/WsNFe2/lote")
public class ReqConsultaLote {

    @XmlElement(name = "Cabecalho", required = true)
    protected ReqConsultaLote.Cabecalho cabecalho;

    /**
     * Gets the value of the cabecalho property.
     * 
     * @return
     *     possible object is
     *     {@link ReqConsultaLote.Cabecalho }
     *     
     */
    public ReqConsultaLote.Cabecalho getCabecalho() {
        return cabecalho;
    }

    /**
     * Sets the value of the cabecalho property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReqConsultaLote.Cabecalho }
     *     
     */
    public void setCabecalho(ReqConsultaLote.Cabecalho value) {
        this.cabecalho = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CodCidade" type="{http://localhost:8080/WsNFe2/tp}tpCodCidade"/>
     *         &lt;element name="CPFCNPJRemetente" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJ"/>
     *         &lt;element name="Versao" type="{http://localhost:8080/WsNFe2/tp}tpVersao"/>
     *         &lt;element name="NumeroLote" type="{http://localhost:8080/WsNFe2/tp}tpNumero"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codCidade",
        "cpfcnpjRemetente",
        "versao",
        "numeroLote"
    })
    public static class Cabecalho {

        @XmlElement(name = "CodCidade")
        protected long codCidade;
        @XmlElement(name = "CPFCNPJRemetente", required = true)
        protected String cpfcnpjRemetente;
        @XmlElement(name = "Versao")
        protected long versao;
        @XmlElement(name = "NumeroLote")
        protected int numeroLote;

        /**
         * Gets the value of the codCidade property.
         * 
         */
        public long getCodCidade() {
            return codCidade;
        }

        /**
         * Sets the value of the codCidade property.
         * 
         */
        public void setCodCidade(long value) {
            this.codCidade = value;
        }

        /**
         * Gets the value of the cpfcnpjRemetente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCPFCNPJRemetente() {
            return cpfcnpjRemetente;
        }

        /**
         * Sets the value of the cpfcnpjRemetente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCPFCNPJRemetente(String value) {
            this.cpfcnpjRemetente = value;
        }

        /**
         * Gets the value of the versao property.
         * 
         */
        public long getVersao() {
            return versao;
        }

        /**
         * Sets the value of the versao property.
         * 
         */
        public void setVersao(long value) {
            this.versao = value;
        }

        /**
         * Gets the value of the numeroLote property.
         * 
         */
        public int getNumeroLote() {
            return numeroLote;
        }

        /**
         * Sets the value of the numeroLote property.
         * 
         */
        public void setNumeroLote(int value) {
            this.numeroLote = value;
        }

    }

}
