//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.19 at 01:26:29 PM BRT 
//


package br.com.dsfnet.nfse.wsnfe2.tp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.wsnfe2.tp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.wsnfe2.tp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TpLote }
     * 
     */
    public TpLote createTpLote() {
        return new TpLote();
    }

    /**
     * Create an instance of {@link TpNotasCancelamentoNFSe }
     * 
     */
    public TpNotasCancelamentoNFSe createTpNotasCancelamentoNFSe() {
        return new TpNotasCancelamentoNFSe();
    }

    /**
     * Create an instance of {@link TpConsultaNFSe }
     * 
     */
    public TpConsultaNFSe createTpConsultaNFSe() {
        return new TpConsultaNFSe();
    }

    /**
     * Create an instance of {@link TpListaItens }
     * 
     */
    public TpListaItens createTpListaItens() {
        return new TpListaItens();
    }

    /**
     * Create an instance of {@link TpDetalhesConsultaRPS }
     * 
     */
    public TpDetalhesConsultaRPS createTpDetalhesConsultaRPS() {
        return new TpDetalhesConsultaRPS();
    }

    /**
     * Create an instance of {@link TpRetornoNotasCancelamentoNFSe }
     * 
     */
    public TpRetornoNotasCancelamentoNFSe createTpRetornoNotasCancelamentoNFSe() {
        return new TpRetornoNotasCancelamentoNFSe();
    }

    /**
     * Create an instance of {@link TpListaNFSe }
     * 
     */
    public TpListaNFSe createTpListaNFSe() {
        return new TpListaNFSe();
    }

    /**
     * Create an instance of {@link TpNotaCancelamentoNFSe }
     * 
     */
    public TpNotaCancelamentoNFSe createTpNotaCancelamentoNFSe() {
        return new TpNotaCancelamentoNFSe();
    }

    /**
     * Create an instance of {@link TpCPFCNPJ2 }
     * 
     */
    public TpCPFCNPJ2 createTpCPFCNPJ2() {
        return new TpCPFCNPJ2();
    }

    /**
     * Create an instance of {@link TpChaveSubstituicaoNFSe }
     * 
     */
    public TpChaveSubstituicaoNFSe createTpChaveSubstituicaoNFSe() {
        return new TpChaveSubstituicaoNFSe();
    }

    /**
     * Create an instance of {@link TpDeducoes }
     * 
     */
    public TpDeducoes createTpDeducoes() {
        return new TpDeducoes();
    }

    /**
     * Create an instance of {@link TpListaErros }
     * 
     */
    public TpListaErros createTpListaErros() {
        return new TpListaErros();
    }

    /**
     * Create an instance of {@link TpInformacoesLote }
     * 
     */
    public TpInformacoesLote createTpInformacoesLote() {
        return new TpInformacoesLote();
    }

    /**
     * Create an instance of {@link TpListaNFSeRPS }
     * 
     */
    public TpListaNFSeRPS createTpListaNFSeRPS() {
        return new TpListaNFSeRPS();
    }

    /**
     * Create an instance of {@link TpEvento }
     * 
     */
    public TpEvento createTpEvento() {
        return new TpEvento();
    }

    /**
     * Create an instance of {@link TpListaNFSeConsultaNota }
     * 
     */
    public TpListaNFSeConsultaNota createTpListaNFSeConsultaNota() {
        return new TpListaNFSeConsultaNota();
    }

    /**
     * Create an instance of {@link TpNotaConsultaNFSe }
     * 
     */
    public TpNotaConsultaNFSe createTpNotaConsultaNFSe() {
        return new TpNotaConsultaNFSe();
    }

    /**
     * Create an instance of {@link TpRPSConsultaNFSe }
     * 
     */
    public TpRPSConsultaNFSe createTpRPSConsultaNFSe() {
        return new TpRPSConsultaNFSe();
    }

    /**
     * Create an instance of {@link TpBairroCompleto }
     * 
     */
    public TpBairroCompleto createTpBairroCompleto() {
        return new TpBairroCompleto();
    }

    /**
     * Create an instance of {@link TpRPSsConsultaNFSe }
     * 
     */
    public TpRPSsConsultaNFSe createTpRPSsConsultaNFSe() {
        return new TpRPSsConsultaNFSe();
    }

    /**
     * Create an instance of {@link TpEndereco }
     * 
     */
    public TpEndereco createTpEndereco() {
        return new TpEndereco();
    }

    /**
     * Create an instance of {@link TpItens }
     * 
     */
    public TpItens createTpItens() {
        return new TpItens();
    }

    /**
     * Create an instance of {@link TpNotasConsultaNFSe }
     * 
     */
    public TpNotasConsultaNFSe createTpNotasConsultaNFSe() {
        return new TpNotasConsultaNFSe();
    }

    /**
     * Create an instance of {@link TpChaveNFeRPS }
     * 
     */
    public TpChaveNFeRPS createTpChaveNFeRPS() {
        return new TpChaveNFeRPS();
    }

    /**
     * Create an instance of {@link TpLoteCancelamentoNFSe }
     * 
     */
    public TpLoteCancelamentoNFSe createTpLoteCancelamentoNFSe() {
        return new TpLoteCancelamentoNFSe();
    }

    /**
     * Create an instance of {@link TpListaDetalhesConsultaRPS }
     * 
     */
    public TpListaDetalhesConsultaRPS createTpListaDetalhesConsultaRPS() {
        return new TpListaDetalhesConsultaRPS();
    }

    /**
     * Create an instance of {@link TpListaDeducoes }
     * 
     */
    public TpListaDeducoes createTpListaDeducoes() {
        return new TpListaDeducoes();
    }

    /**
     * Create an instance of {@link TpLogradouroCompleto }
     * 
     */
    public TpLogradouroCompleto createTpLogradouroCompleto() {
        return new TpLogradouroCompleto();
    }

    /**
     * Create an instance of {@link TpChaveNFe }
     * 
     */
    public TpChaveNFe createTpChaveNFe() {
        return new TpChaveNFe();
    }

    /**
     * Create an instance of {@link TpChaveRPS }
     * 
     */
    public TpChaveRPS createTpChaveRPS() {
        return new TpChaveRPS();
    }

    /**
     * Create an instance of {@link TpLoteConsultaNFSe }
     * 
     */
    public TpLoteConsultaNFSe createTpLoteConsultaNFSe() {
        return new TpLoteConsultaNFSe();
    }

    /**
     * Create an instance of {@link TpListaAlertas }
     * 
     */
    public TpListaAlertas createTpListaAlertas() {
        return new TpListaAlertas();
    }

    /**
     * Create an instance of {@link TpRPS }
     * 
     */
    public TpRPS createTpRPS() {
        return new TpRPS();
    }

    /**
     * Create an instance of {@link TpNFSe }
     * 
     */
    public TpNFSe createTpNFSe() {
        return new TpNFSe();
    }

}
