//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.19 at 01:26:29 PM BRT 
//


package br.com.dsfnet.nfse.wsnfe2.tp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tpTributacao.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tpTributacao">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="K"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="M"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tpTributacao")
@XmlEnum
public enum TpTributacao {


    /**
     * Isenta de ISS.
     * 
     */
    C,

    /**
     * Imune.
     * 
     */
    F,

    /**
     * Depósito em Juízo.
     * 
     */
    K,

    /**
     * Não Incidente no Município.
     * 
     */
    E,

    /**
     * Tributável
     * 
     */
    T,

    /**
     * Tributável Simples Nacional.
     * 
     */
    H,

    /**
     * Tributável Fixo.
     * 
     */
    G,

    /**
     * Não Tributável.
     * 
     */
    N,

    /**
     * Tributação Microempresário Individual (MEI)
     * 
     */
    M;

    public String value() {
        return name();
    }

    public static TpTributacao fromValue(String v) {
        return valueOf(v);
    }

}
