//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 10:52:18 AM BRST 
//


package br.com.dsfnet.nfse.wsnfe2.lote.retornoConsultaNotas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.dsfnet.nfse.wsnfe2.tp.TpListaErros;
import br.com.dsfnet.nfse.wsnfe2.tp.TpListaNFSeConsultaNota;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cabecalho">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CodCidade" type="{http://localhost:8080/WsNFe2/tp}tpCodCidade"/>
 *                   &lt;element name="CPFCNPJRemetente" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJ"/>
 *                   &lt;element name="InscricaoMunicipalPrestador" type="{http://localhost:8080/WsNFe2/tp}tpInscricaoMunicipal"/>
 *                   &lt;element name="dtInicio" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="dtFim" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="Versao" type="{http://localhost:8080/WsNFe2/tp}tpVersao"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Notas" type="{http://localhost:8080/WsNFe2/tp}tpListaNFSeConsultaNota" minOccurs="0"/>
 *         &lt;element name="Erros" type="{http://localhost:8080/WsNFe2/tp}tpListaErros" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cabecalho",
    "notas",
    "erros"
})
@XmlRootElement(name = "RetornoConsultaNotas")
public class RetornoConsultaNotas {

    @XmlElement(name = "Cabecalho", required = true)
    protected RetornoConsultaNotas.Cabecalho cabecalho;
    @XmlElement(name = "Notas")
    protected TpListaNFSeConsultaNota notas;
    @XmlElement(name = "Erros")
    protected TpListaErros erros;

    /**
     * Gets the value of the cabecalho property.
     * 
     * @return
     *     possible object is
     *     {@link RetornoConsultaNotas.Cabecalho }
     *     
     */
    public RetornoConsultaNotas.Cabecalho getCabecalho() {
        return cabecalho;
    }

    /**
     * Sets the value of the cabecalho property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetornoConsultaNotas.Cabecalho }
     *     
     */
    public void setCabecalho(RetornoConsultaNotas.Cabecalho value) {
        this.cabecalho = value;
    }

    /**
     * Gets the value of the notas property.
     * 
     * @return
     *     possible object is
     *     {@link TpListaNFSeConsultaNota }
     *     
     */
    public TpListaNFSeConsultaNota getNotas() {
        return notas;
    }

    /**
     * Sets the value of the notas property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpListaNFSeConsultaNota }
     *     
     */
    public void setNotas(TpListaNFSeConsultaNota value) {
        this.notas = value;
    }

    /**
     * Gets the value of the erros property.
     * 
     * @return
     *     possible object is
     *     {@link TpListaErros }
     *     
     */
    public TpListaErros getErros() {
        return erros;
    }

    /**
     * Sets the value of the erros property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpListaErros }
     *     
     */
    public void setErros(TpListaErros value) {
        this.erros = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CodCidade" type="{http://localhost:8080/WsNFe2/tp}tpCodCidade"/>
     *         &lt;element name="CPFCNPJRemetente" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJ"/>
     *         &lt;element name="InscricaoMunicipalPrestador" type="{http://localhost:8080/WsNFe2/tp}tpInscricaoMunicipal"/>
     *         &lt;element name="dtInicio" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="dtFim" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="Versao" type="{http://localhost:8080/WsNFe2/tp}tpVersao"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codCidade",
        "cpfcnpjRemetente",
        "inscricaoMunicipalPrestador",
        "dtInicio",
        "dtFim",
        "versao"
    })
    public static class Cabecalho {

        @XmlElement(name = "CodCidade")
        protected long codCidade;
        @XmlElement(name = "CPFCNPJRemetente", required = true)
        protected String cpfcnpjRemetente;
        @XmlElement(name = "InscricaoMunicipalPrestador")
        protected long inscricaoMunicipalPrestador;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dtInicio;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dtFim;
        @XmlElement(name = "Versao")
        protected long versao;

        /**
         * Gets the value of the codCidade property.
         * 
         */
        public long getCodCidade() {
            return codCidade;
        }

        /**
         * Sets the value of the codCidade property.
         * 
         */
        public void setCodCidade(long value) {
            this.codCidade = value;
        }

        /**
         * Gets the value of the cpfcnpjRemetente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCPFCNPJRemetente() {
            return cpfcnpjRemetente;
        }

        /**
         * Sets the value of the cpfcnpjRemetente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCPFCNPJRemetente(String value) {
            this.cpfcnpjRemetente = value;
        }

        /**
         * Gets the value of the inscricaoMunicipalPrestador property.
         * 
         */
        public long getInscricaoMunicipalPrestador() {
            return inscricaoMunicipalPrestador;
        }

        /**
         * Sets the value of the inscricaoMunicipalPrestador property.
         * 
         */
        public void setInscricaoMunicipalPrestador(long value) {
            this.inscricaoMunicipalPrestador = value;
        }

        /**
         * Gets the value of the dtInicio property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDtInicio() {
            return dtInicio;
        }

        /**
         * Sets the value of the dtInicio property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDtInicio(XMLGregorianCalendar value) {
            this.dtInicio = value;
        }

        /**
         * Gets the value of the dtFim property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDtFim() {
            return dtFim;
        }

        /**
         * Sets the value of the dtFim property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDtFim(XMLGregorianCalendar value) {
            this.dtFim = value;
        }

        /**
         * Gets the value of the versao property.
         * 
         */
        public long getVersao() {
            return versao;
        }

        /**
         * Sets the value of the versao property.
         * 
         */
        public void setVersao(long value) {
            this.versao = value;
        }

    }

}
